// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzCcmtKHRAVy1ZhUcvAkVgrGrNIkwch0',
    appId: '1:234432157489:web:02c662ea94bcce1f410210',
    messagingSenderId: '234432157489',
    projectId: 'enoikiou',
    authDomain: 'enoikiou.firebaseapp.com',
    storageBucket: 'enoikiou.appspot.com',
    measurementId: 'G-2BV6HFS6RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3aePanRIpdLNO8-Dvskr76MV-Js6tEng',
    appId: '1:234432157489:android:5a715cbc3816c2bf410210',
    messagingSenderId: '234432157489',
    projectId: 'enoikiou',
    storageBucket: 'enoikiou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Q6X_DBXcCbaltp67b6o5ozdthLNSzQo',
    appId: '1:234432157489:ios:a870444d253b47ae410210',
    messagingSenderId: '234432157489',
    projectId: 'enoikiou',
    storageBucket: 'enoikiou.appspot.com',
    iosBundleId: 'com.example.enoikiou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Q6X_DBXcCbaltp67b6o5ozdthLNSzQo',
    appId: '1:234432157489:ios:a870444d253b47ae410210',
    messagingSenderId: '234432157489',
    projectId: 'enoikiou',
    storageBucket: 'enoikiou.appspot.com',
    iosBundleId: 'com.example.enoikiou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALzCcmtKHRAVy1ZhUcvAkVgrGrNIkwch0',
    appId: '1:234432157489:web:017792b820c2c1f6410210',
    messagingSenderId: '234432157489',
    projectId: 'enoikiou',
    authDomain: 'enoikiou.firebaseapp.com',
    storageBucket: 'enoikiou.appspot.com',
    measurementId: 'G-6JM2D6Y8J5',
  );
}
